# Intro to Numpy

In [1]:
import sys
import numpy as np

# Numpy Arrays

In [2]:
np.array([10, 22, 32, 44])

array([10, 22, 32, 44])

In [3]:
a = np.array([10, 22, 32, 44])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(10, 22)

In [6]:
a[0:]

array([10, 22, 32, 44])

In [7]:
a[1:3]

array([22, 32])

In [8]:
a[1:-1]

array([22, 32])

In [9]:
a[::2]

array([10, 32])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])


# Array Types

In [13]:
a

array([10, 22, 32, 44])

In [14]:
a.dtype

dtype('int32')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [17]:
a,b

(array([10, 22, 32, 44]), array([0. , 0.5, 1. , 1.5, 2. ]))

In [20]:
np.array([1, 2, 3, 4], dtype=np.float)

C:\Users\priya\AppData\Local\Temp\ipykernel_30092\217965920.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)


array([1., 2., 3., 4.])

In [21]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [22]:
c = np.array(['a', 'b', 'c'])

In [23]:
c.dtype

dtype('<U1')

In [24]:
d = np.array([{'a': 1}, sys])

In [25]:
d.dtype

dtype('O')

# Dimesnsions and shapes

In [26]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [27]:
A.shape

(2, 3)

In [28]:
A.ndim

2

In [29]:
A.size

6

In [30]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [31]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [36]:
B.dtype

dtype('int32')

In [37]:
B.size

12

In [34]:
B.size

12

In [38]:
type(B[0])

numpy.ndarray

# Indexing and Slicing of Matrices

In [40]:

A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [41]:
A[1]

array([4, 5, 6])

In [42]:
A[1][0]

4

In [43]:
A[1, 0]

4

In [44]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [46]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [47]:
A[:2, 2:]

array([[3],
       [6]])

In [48]:
A[2] = 99

In [49]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

# Summary statistics

In [50]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [51]:
a.mean()

2.5

In [52]:
a.std()

1.118033988749895

In [53]:
a.var()

1.25

In [57]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [58]:
A.sum(axis=0)

array([12, 15, 18])

In [59]:
A.sum(axis=1)

array([ 6, 15, 24])

In [60]:
A.mean(axis=0)

array([4., 5., 6.])

In [61]:
A.mean(axis=1)

array([2., 5., 8.])

In [62]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [63]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

# Broadcasting and Vectorized operations

In [64]:
a = np.arange(4)

In [65]:
a

array([0, 1, 2, 3])

In [66]:
a + 10

array([10, 11, 12, 13])

In [67]:
a * 10

array([ 0, 10, 20, 30])

In [68]:
a

array([0, 1, 2, 3])

In [69]:
a += 100

In [70]:
a

array([100, 101, 102, 103])

In [71]:
l = [0, 1, 2, 3]
[i * 10 for i in l]

[0, 10, 20, 30]

In [72]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [73]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [74]:
a+b

array([10, 11, 12, 13])

In [75]:
a * b

array([ 0, 10, 20, 30])

# Boolean arrays

In [76]:
a

array([0, 1, 2, 3])

In [78]:
a[0], a[-1]


(0, 3)

In [79]:
a[[0, -1]]

array([0, 3])

In [80]:
a[[True, False, False, True]]

array([0, 3])

In [81]:
a >= 20

array([False, False, False, False])

In [82]:
a.mean()

1.5

In [83]:
a[a > a.mean()]

array([2, 3])

In [84]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [85]:
A = np.random.randint(100, size=(3, 3))

In [86]:
A

array([[77, 57, 16],
       [43,  5, 35],
       [68, 99, 51]])

In [87]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([77, 16,  5, 68, 51])

In [88]:
A < 20

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])

In [89]:
A[A > 30]

array([77, 57, 43, 35, 68, 99, 51])

# Linear Algebra

In [93]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])



In [94]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
    ])

In [95]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [96]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [97]:
B .T

array([[6, 4, 2],
       [5, 3, 1]])

In [98]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

# Size of objects in Memory

##  Int, floats

In [111]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [112]:
# Longs are even larger
sys.getsizeof(10**100)
72

72

In [113]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [114]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [115]:
np.dtype(float).itemsize

8

# Lists are even larger

In [116]:
# A one-element list
sys.getsizeof([1])


64

In [117]:
# An array of one element in numpy
np.array([1]).nbytes

4

# Performance is also important

In [119]:
l = list(range(100000))
a = np.arange(100000)
%time np.sum(a ** 2)



CPU times: total: 0 ns
Wall time: 179 µs


216474736

In [120]:
%time sum([x ** 2 for x in l])

CPU times: total: 46.9 ms
Wall time: 53.3 ms


333328333350000

# Useful Numpy functions

## Random

In [124]:
np.random.random(size=2)


array([0.83250538, 0.93616882])

In [125]:
np.random.normal(size=2)

array([-0.02613507, -2.4707354 ])

In [126]:
np.random.rand(2, 4)

array([[0.27113246, 0.60428922, 0.46267687, 0.94214119],
       [0.33208028, 0.24826115, 0.5267576 , 0.47948356]])

# Arrange

In [129]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [131]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

# Reshape

In [133]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [134]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Linespace

In [136]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [137]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [138]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

# zeros, ones, empty

In [149]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [150]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [152]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [153]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [154]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [155]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

# Identity and eye

In [157]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [158]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [159]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [160]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [161]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [162]:
"Hello World"[6]

'W'